version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_floaty"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_floaty/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_floaty_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_floaty_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_floaty_ios"
    schedule:
      interval: "daily"