name: flutter_floaty

#description of the package
description:  >-
  This plugin provides a customizable Floating button to drag 
  on screen in flutter. This package is light and easy to use

version: 0.1.9

#package homepage:
homepage: https://github.com/JordyHers/flutter_floaty

#package repository
repository: https://github.com/JordyHers/flutter_floaty

funding:
  - https://patreon.com/user?u=91968185

#supported platforms
platforms:
  android:
  ios:

#licence supported
license: MIT

false_secrets:
  - README.md

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
