name: flutter_floaty
description: Floating and draggable flutter button
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"



dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
