name: flutter_floaty

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/flutter_floaty.yaml"
      - "flutter_floaty/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/flutter_floaty.yaml"
      - "flutter_floaty/**"

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.19.0
      working_directory: flutter_floaty


  android:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: flutter_floaty/example

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2




  ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: flutter_floaty/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli



